### ISSUE TITLE
Locally installed version of solc is outdated -> poor linting

### ISSUE THREAD

**Issue by kerzhner** [statechannels/nitro-protocol#56]
`solc` package is pulled in as a dependency of `jest-gas-reporter` and `magmo-devtools`. The `solidity` VSCode extension uses local `solc` for linting. This causes a couple issues:
- Error on the `pragma solidity ^0.5.11;` line.
- More importantly, it seems like the above error results in other errors not being flagged by the linter.

To reproduce:
- Introduce a solidity error. For example, replace a `function` keyword with invalid `functions`. Observe no error flagged.
- Remove the `pragma solidity ^0.5.11;`. Observe the error flagged.

**Comment by andrewgordstewart** [comment]
It's not obvious to me that the solution to this problem is to upgrade the version of `solc` in some tooling dependencies. Indeed, I'm not sure it's good to explicitly depend on secondary dependencies, since `package.json` can make no guarantee of even the existence of those dependencies.

Since the contracts specify that they require a solidity version satisfying `^0.5.11`, does it make sense to make `solc` a devDependency of this repo, specifying that version?

**Comment by kerzhner** [comment]
That's a good thought. Originally, I dismissed adding `solc` as devDependency as it appeared that the solidity plugin was using the oldest version of `solc` installed locally. However, it looks like when `solc` is declared as a devDependency, that version of `solc` is used (and not an older version brought in by another package).

**Comment by andrewgordstewart** [comment]
I think this is what's happening:
## Currently
- Both `jest-gas-reporter` and `magmo-devtools` require solc at version `0.5.7`
- Yarn recognizes this, and installs version 0.5.7 of solc in `$PROJECT_ROOT/node_modules/solc`

## If you update solc in `jest-gas-reporter` and `magmo-devtools`
- This would simply change the version of solc in `$PROJECT_ROOT/node_modules/solc` to the updated version

## If you don't update solc in `jest-gas-reporter` and `magmo-devtools`, but add solc as a dev dep
- Yarn would recognize that `magmo-devtools` requires solc at the pinned version 0.5.7, but the project requires it at say `^0.5.11`
- Since `0.5.7` does not match `^0.5.11`, yarn would install solc at version `0.5.7` in  `$PROJECT_ROOT/node_modules/magmo-devtools/solc`
- Ditto for `jest-gas-reporter`
- Yarn would then install the most recent version of `solc` satisfying `^0.5.11` in  `$PROJECT_ROOT/node_modules/solc`

## Pure speculation
The solidity plugin uses the solc installed at `$PROJECT_ROOT/node_modules/solc`

If this is true, that would explain why installing as a dev dependency resolves the issue. I think it would also work if you upgraded solc in just one of `magmo-devtools` or `jest-gas-reporter`.

**Comment by andrewgordstewart** [comment]
The speculation is based off of some part of the plugin like [this line](https://github.com/juanfranblanco/vscode-solidity/blob/master/src/solcCompiler.ts#L3). I'm not gonna bother to work through it entirely, but if we were using an older version of the plugin (say, one where [this](https://github.com/juanfranblanco/vscode-solidity/blob/master/package.json#L64) says `^0.5.5`), I'm pretty sure that would explain the behaviour we saw.

**Comment by andrewgordstewart** [comment]
Note:
>Both jest-gas-reporter and magmo-devtools require solc at version 0.5.7

this wasn't actually correct: `magmo-devtools` had version 0.5.10 installed for me, at `$ROOT/node_modules/magmo-devtools/solc`
